### ISSUE TITLE
The ilmbase build includes openexr!

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/ilmbase-feedstock#2]
We should probably drop openexr which should be a separate package.

**Comment by npavlovikj** [comment]
@SylvainCorlay , I believe this build only contains "ilmbase", since only the "ilmbase" libraries and release are installed and used in this recipe. Is there a reason why you think "openexr" is installed as well?

**Comment by SylvainCorlay** [comment]
- The recipe fetches the sources from openexr:

   ```
   url: https://github.com/openexr/openexr/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz
   ```

   (which happen to vendor ilmbase as part of its source tree).

- The recipe checks that openexr headers are installed

   ```
    - test -f ${PREFIX}/include/OpenEXR/half.h                    # [unix]
    - test -f ${PREFIX}/include/OpenEXR/IlmThread.h               # [unix]
    - test -f ${PREFIX}/include/OpenEXR/ImathMath.h               # [unix]
    - test -f ${PREFIX}/include/OpenEXR/Iex.h                     # [unix]
    - test -f ${PREFIX}/include/OpenEXR/IexMathExc.h              # [unix]
   ```

- The `build.sh` calls the general makefile for openexr.

**Comment by SylvainCorlay** [comment]
(I came across this as I was working on packaging openexr, and tried to depend on ilmbase instead of vendoring it, and had a quick read of the recipe.)

**Comment by SylvainCorlay** [comment]
Hum, this is really confusing. This actually downloads the ilmbase tarball, which apparently includes headers installed in `PREFIX/include/OpenEXR`.

**Comment by npavlovikj** [comment]
Thanks for the clarification @SylvainCorlay . 

Although the source tree is the same for all "openexr" dependencies, this recipe only downloads and  installs "ilmbase". As stated in the documentation, https://github.com/openexr/openexr, "ilmbase" installs the headers "Half, Imath, Iex, IlmThread", which are the ones you have pointed above. "openexr" has additional headers that are not part of this recipe. Also, the "cmake" flags for "ilmbase" differ from the ones for "openexr", and the remaining dependencies are not installed as part of this recipe.

I was working on the "openexr" recipe myself, and therefore I wanted to create the separate packages for "ilmbase" and "pyilmbase" (but got stuck with "pyilmbase" unfortunately).
I did some reading and searching about installing the "openexr" dependencies, but if you think the recipe is wrong, please feel free to modify it accordingly.

**Comment by SylvainCorlay** [comment]
Sorry for the noise, I got confused by the URL and the installation of headers into `PREFIX/include/OpenEXR`...

**Comment by SylvainCorlay** [comment]
I am working on the openexr packaging here: https://github.com/conda-forge/staged-recipes/pull/7088

Do you want to be added to the maintainers? I am skipping the pyilmbase which could be in a separate package.

**Comment by npavlovikj** [comment]
No problem at all @SylvainCorlay , I am glad we figured that out. "openexr" is quite complicated package and there is lots of inconsistency in its documentation...

Sure, if it is ok with you, I wouldn't mind being added as a maintainer to the package.

**Comment by SylvainCorlay** [comment]
Thanks!
